version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: rentpro-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: rentpro_db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rentpro-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      MONGO_URI: mongodb://mongo:27017/rentpro_db
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rentpro-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
